### ISSUE TITLE
Can't start？

### ISSUE THREAD

**Issue by ettingshausen** [Dr-kyle/kafka-eagle-docker#1]
```
sh: can't open '/app/kafka-eagle/bin/ke.sh start && tail -f /app/kafka-eagle/logs/log.log': No such file or directory
``` 
![截屏2020-03-2015 21 45](https://user-images.githubusercontent.com/9806325/77143557-8a9b8580-6abe-11ea-9c47-946408b67fdc.png)

**Comment by Dr-kyle** [comment]
你修改了log4j.properties 这个配置里面的日志路径吗？

**Comment by Dr-kyle** [comment]
> ```
> sh: can't open '/app/kafka-eagle/bin/ke.sh start && tail -f /app/kafka-eagle/logs/log.log': No such file or directory
> ```
> 
> ![截屏2020-03-2015 21 45](https://user-images.githubusercontent.com/9806325/77143557-8a9b8580-6abe-11ea-9c47-946408b67fdc.png)

你修改了log4j.properties 这个配置里面的日志路径吗？

**Comment by ettingshausen** [comment]
没有，只是改了下volume映射路径

**Comment by Dr-kyle** [comment]
这个是我的问题，应该是 /app/kafka-eagle/logs/log.log 这个文件还没生成，我为了在docker日志能看到这个，所以加了 tail -f /app/kafka-eagle/logs/log.log 这个命令，  暂时你可以将这个文件映射到机器上，(最好创建一个空的文件 log.log)然后启动试试看

**Comment by Dr-kyle** [comment]
我接下来修改下这个问题

**Comment by ettingshausen** [comment]
看起来还是不行
![截屏2020-03-2016 48 06](https://user-images.githubusercontent.com/9806325/77148548-b886c700-6aca-11ea-837d-bdb8808c3b57.png)

**Comment by Dr-kyle** [comment]
你拉这个镜像试一下 docker pull xianlab/kafka-eagle:v1.4.1， 用这个版本的镜像启动试一下，latest的镜像好像不是最新的代码，可能是我测试时候使用的

**Comment by Dr-kyle** [comment]
1. docker pull xianlab/kafka-eagle:v1.4.1
2. docker run --name kafka-eagle --net host \
-v /conf/system-config.properties:/app/kafka-eagle/conf/system-config.properties \
xianlab/kafka-eagle:v1.4.1

**Comment by Dr-kyle** [comment]
可以了吗？

**Comment by ettingshausen** [comment]
> 1. docker pull xianlab/kafka-eagle:v1.4.1
> 2. docker run --name kafka-eagle --net host 
>    -v /conf/system-config.properties:/app/kafka-eagle/conf/system-config.properties 
>    xianlab/kafka-eagle:v1.4.1

这个镜像是可以的。

**Comment by Dr-kyle** [comment]
恩，latest镜像应该是我测试的时候用的，没有及时更新

**Comment by ettingshausen** [comment]
OK
